# Generated by Django 5.1.3 on 2024-11-13 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название машины')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('year', models.CharField(max_length=80, verbose_name='Год машины')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
                ('description', models.TextField(verbose_name='Описание машины')),
                ('generation', models.CharField(max_length=255, verbose_name='Поколение')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('volume', models.CharField(max_length=100, verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание гайда')),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Гайд',
                'verbose_name_plural': 'Гайды',
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
