# Generated by Django 5.1.3 on 2024-11-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineapp', '0002_ad_guide_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
