# Generated by Django 5.1.3 on 2024-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineapp', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('engine_volume', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.DeleteModel(
            name='ad',
        ),
    ]
